# Generated by Django 4.2.6 on 2023-10-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DocketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hours_worked', models.FloatField()),
                ('rate_per_hour', models.FloatField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockers.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=255)),
                ('chg', models.CharField(blank=True, max_length=255, null=True)),
                ('com', models.CharField(blank=True, max_length=255, null=True)),
                ('docket_type', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField()),
                ('buyer', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('item', models.CharField(max_length=255)),
                ('commodity_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('order_value', models.FloatField()),
                ('amount_invoiced', models.FloatField()),
                ('wbs_code', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('po_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockers.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockers.supplier')),
            ],
        ),
    ]
